image: python:3-slim

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - test
  - release
  - pages

test:
  before_script:
    - python -V
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
  script:
    - pip install -r requirements.txt
    - pip install pytest yamllint setuptools pytest_httpserver
    - python -m pytest
    - python -m yamllint apis/
  except:
    - release

release:
  image: node:current-alpine
  stage: release
  script:
    - npm install semantic-release @semantic-release/gitlab @semantic-release/changelog conventional-changelog-eslint
    - npx semantic-release
  only:
    - release

pages:
  script:
    - pip install sphinx sphinx-rtd-theme sphinxcontrib-napoleon
    - cd doc ; make html
    - mv _build/html/ ../public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

